name: flutter_archkit
description: An automated Flutter architecture generator (Clean, MVVM, MVC with Bloc, Cubit, Riverpod, Provider, GetX), feature module generator, and multi-flavor CLI configuration tool.
version: 0.1.0
homepage: https://github.com/Sangramdeve/flutter_archkit
repository: https://github.com/Sangramdeve/flutter_archkit
issue_tracker: https://github.com/Sangramdeve/flutter_archkit/issues
topics:
  - flutter
  - architecture
  - clean-architecture
  - mvvm
  - flavor

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=1.17.0"

executables:
  archkit: archkit
  setup_flavor: setup_flavor

dependencies:
  flutter:
    sdk: flutter
  path: ^1.9.0
  yaml: ^3.1.2
  dart_xcodeproj: ^0.3.0
  args: ^2.7.0
  interact: ^2.2.0
  mason_logger: ^0.3.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
