/// Strongly typed runtime server configuration generated by `flutter_archkit:setup_flavor`
class ServerConfig {
  final String environment;
  final String appName;
  final String baseUrl;

  const ServerConfig({
    required this.environment,
    required this.appName,
    required this.baseUrl,
  });

  static const ServerConfig dev = ServerConfig(
    environment: 'development',
    appName: 'ArchKit Demo (Dev)',
    baseUrl: 'https://dev-api.archkit.example.com',
  );

  static const ServerConfig prod = ServerConfig(
    environment: 'production',
    appName: 'ArchKit Demo',
    baseUrl: 'https://api.archkit.example.com',
  );
}
