import 'dart:io';
import '../parser/flavor_config.dart';

class AndroidFlavorGenerator {
  static const _startMarker =
      '// >>> FLAVOR_CONFIG_START (generated by flutter_archkit)';
  static const _startMarkerGradle =
      '// ----- BEGIN flavorDimensions (autogenerated by flutter_archkit) -----';
  static const _endMarker = '// <<< autogenerated FLAVOR_CONFIG_END';

  final List<FlavorConfig> flavors;
  final String projectRoot;

  AndroidFlavorGenerator({required this.flavors, required this.projectRoot});

  Future<void> run() async {
    await _createFlavorGradleKts();
    await _updateBuildGradleKts();
  }

  Future<void> _createFlavorGradleKts() async {
    final flavorFile = File('$projectRoot/android/app/flavor.gradle.kts');
    await flavorFile.parent.create(recursive: true);

    final buffer = StringBuffer();
    buffer.writeln(_startMarker);

    buffer.writeln('import com.android.build.gradle.AppExtension');
    buffer.writeln();
    buffer.writeln(
      'val android = project.extensions.getByType(AppExtension::class.java)',
    );
    buffer.writeln();

    buffer.writeln('android.apply {');
    buffer.writeln('    flavorDimensions("default")');
    buffer.writeln();
    buffer.writeln('    productFlavors {');
    for (final flavor in flavors) {
      buffer.writeln('        create("${flavor.name}") {');
      buffer.writeln('            dimension = "default"');
      buffer.writeln(
        '            applicationId = "${flavor.applicationId}"',
      );
      buffer.writeln(
        '            resValue(type = "string", name = "app_name", value = "${flavor.effectiveAndroidAppName}")',
      );
      buffer.writeln('        }');
    }
    buffer.writeln('    }');
    buffer.writeln();
    buffer.writeln('    buildFeatures.resValues = true');
    buffer.writeln('}');
    buffer.writeln(_endMarker);

    final newContent = buffer.toString();

    if (await flavorFile.exists()) {
      final currentContent = await flavorFile.readAsString();
      if (currentContent.contains(_startMarker) &&
          currentContent.contains(_endMarker)) {
        final startIndex = currentContent.indexOf(_startMarker);
        final endIndex =
            currentContent.indexOf(_endMarker) + _endMarker.length;
        final updatedContent = currentContent.replaceRange(
          startIndex,
          endIndex,
          newContent,
        );
        await flavorFile.writeAsString(updatedContent);
        return;
      }
    }

    await flavorFile.writeAsString(newContent);
  }

  Future<void> _updateBuildGradleKts() async {
    final gradleFile = File('$projectRoot/android/app/build.gradle.kts');

    if (!await gradleFile.exists()) {
      stderr.writeln(
        '❌ Could not find android/app/build.gradle.kts. '
        'Run this command from your Flutter project root.',
      );
      return;
    }

    String content = await gradleFile.readAsString();

    // Build the flavor block to inject
    final buffer = StringBuffer();
    buffer.writeln(_startMarkerGradle);

    buffer.writeln('apply { from("flavor.gradle.kts") }');
    buffer.writeln(_endMarker);

    final block = buffer.toString().trimRight();

    if (content.contains(_startMarkerGradle) && content.contains(_endMarker)) {
      final startIndex = content.indexOf(_startMarkerGradle);
      final endIndex = content.indexOf(_endMarker) + _endMarker.length;
      content = content.replaceRange(startIndex, endIndex, block);
    } else {
      if (content.isNotEmpty && !content.endsWith('\n')) {
        content += '\n';
      }
      content += '\n$block\n';
    }

    await gradleFile.writeAsString(content);
    stdout.writeln('✏️  Updated android/app/build.gradle.kts');
  }
}
